---
kind: pipeline
type: docker
name: make

steps:
- name: make project
  image: aergus/latex:2024-05-12
  commands:
    - make clean -C ./docs
    - make all -C ./docs

- name: pdf push main
  image: aergus/latex:2024-05-12
  commands:
    - git add ./docs/thesis.pdf -f
    - git commit -m "Update PDF automatically [CI SKIP]"
    - git push --set-upstream origin main  
  when:
    branch:
      - main
    status:
      - success
  depends_on:
    - make project
