---
kind: pipeline
type: docker
name: make

steps:
- name: make project
  image: leplusorg/latex
  commands:
    - make nuke
    - make all

- name: pdf push main
  image: leplusorg/latex
  commands:
    - git add ./docs/thesis.pdf
    - git commit -m "Update PDF automatically [CI SKIP]"
    - git push --set-upstream origin main  
  when:
    branch:
      - main
    status:
      - success
  depends_on:
    - make project
